{{- if and .Values.serviceAccount.create .Values.gateway.enabled -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "aigent.serviceAccountName" . }}
  labels:
    {{- include "aigent.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "aigent.serviceAccountName" . }}
subjects:
  - kind: ServiceAccount
    name: {{ include "aigent.serviceAccountName" . }}
    namespace: {{ .Release.Namespace }}
{{- end }}
