---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-otelhttp
  labels:
spec:
  type: {{ .Values.service.otelhttp.type }}
  selector:
    app: {{ .Release.Name }}
  ports:
    - protocol: TCP
      port:  {{ .Values.service.otelhttp.port }}
      targetPort: {{ .Values.service.otelhttp.port }}
{{- if eq .Values.service.otelhttp.type "NodePort" }}
      nodePort: {{ .Values.service.otelhttp.nodePort }}
{{- end }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-otelgrpc
  labels:
spec:
  type: {{ .Values.service.otelgrpc.type }}
  selector:
    app: {{ .Release.Name }}
  ports:
    - protocol: TCP
      port:  {{ .Values.service.otelgrpc.port }}
      targetPort: {{ .Values.service.otelgrpc.port }}
{{- if eq .Values.service.otelgrpc.type "NodePort" }}
      nodePort: {{ .Values.service.otelgrpc.nodePort }}
{{- end }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-statsd
  labels:
spec:
  type: {{ .Values.service.statsd.type }}
  selector:
    app: {{ .Release.Name }}
  ports:
    - protocol: UDP
      port:  {{ .Values.service.statsd.port }}
      targetPort: {{ .Values.service.statsd.port }}
{{- if eq .Values.service.statsd.type "NodePort" }}
      nodePort: {{ .Values.service.statsd.nodePort }}
{{- end }}
